### PR TITLE
Lesson 1.1

### PR DESCRIPTION
**Pull request by stephskas**
Initial commit for Lesson 1.1 working with Lists and JSX

### CODE REVIEW

**Review by leo-mutuku — COMMENTED** [review]
Great.

Suggestions:
One index.html, change the title to a more meaniful name, e.g Lession 1 , Todo List App e.t.c

**Comment by leo-mutuku** [comment]
I will share some guide on git pull, branching and merging. I will als try to have session on git.

**Comment by leo-mutuku** [comment]
Greate work,

Lesson 1 assignment approved.

**Comment by stephskas** [comment]
> I will share some guide on git pull, branching and merging. I will als try to have session on git.

**Comment by leo-mutuku** [comment]
Perfect I see you have merged lesson-1.2 branch successfully. That's a good progress, well I see you are far ahead and doing quite good. Just thought if could hold a private meet for like 10 minutes to add on about git pull, merge and rebase. I wanted to have session on advanced git but it wasn't possible. So if you need some clarity on any of this cmmands just hit on me i will be able to have a onw-on-one session.

**Comment by leo-mutuku** [comment]
A reminder for the branch name, make it more descriptive. For example "Lesson-1.2 React DOM and Component".

**Pull request merged**
